### ISSUE TITLE
Is Detect-Order-Construct open source

### ISSUE THREAD

**Issue by yjmm10** [microsoft/CompHRDoc#1]

**Comment by JarvisUSTC** [comment]
Thank you for your interest in our work. Our Detect-Order-Construct method is now integrated into the [Document Intelligence Studio](https://documentintelligence.ai.azure.com/studio/), which is designed for extracting and analyzing document structures. Due to company policy, we are unable to open-source the source code. However, our methods are straightforward to replicate. Should you have any questions, please do not hesitate to contact me.
